name: Trigger PHP Script

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

jobs:
  trigger_script:
    runs-on: ubuntu-latest

    steps:
      - name: Execute Puppeteer Script
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Puppeteer
        run: |
          npm install puppeteer

      - name: Run Script
        run: |
          node -e "
          const puppeteer = require('puppeteer');
          (async () => {
              const browser = await puppeteer.launch({ args: ['--no-sandbox', '--disable-setuid-sandbox'] });
              const page = await browser.newPage();
              await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36');
              const response = await page.goto('https://cgvacancy.freesite.online/scraper.php', { waitUntil: 'networkidle2' });
              if (response.ok()) {
                  console.log('Script executed successfully.');
              } else {
                  console.log('Failed to execute script. Status:', response.status());
              }
              await browser.close();
          })();
          "
          
