name: Trigger PHP Script

on:
  schedule:
    # Schedule at 12:00 PM, 4:00 PM, and 10:00 PM IST
    - cron: "30 6 * * *"  # 12:00 PM IST (6:30 AM UTC)
    - cron: "30 10 * * *" # 4:00 PM IST (10:30 AM UTC)
    - cron: "30 16 * * *" # 10:00 PM IST (4:30 PM UTC)
  workflow_dispatch:  # Allow manual trigger

jobs:
  trigger_script:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger scraper.php
        run: |
          curl -X GET "https://cgvacancy.freesite.online/scraper.php" \
          -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36"
