name: Trigger PHP Script

on:
  schedule:
    # Run at 12:00 PM, 4:00 PM, and 10:00 PM IST
    - cron: "30 6 * * *"  # 12:00 PM IST (6:30 AM UTC)
    - cron: "30 10 * * *" # 4:00 PM IST (10:30 AM UTC)
    - cron: "30 16 * * *" # 10:00 PM IST (4:30 PM UTC)
  workflow_dispatch:  # Allow manual trigger

jobs:
  execute_script:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/yourusername/puppeteer-image:latest  # Use your custom Docker image

    steps:
      - name: Trigger PHP Script using Puppeteer
        run: |
          node -e "
          const puppeteer = require('puppeteer');
          (async () => {
              const browser = await puppeteer.launch({ headless: true });
              const page = await browser.newPage();
              await page.setUserAgent(
                  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36'
              );
              await page.goto('https://cgvacancy.freesite.online/scraper.php', { waitUntil: 'networkidle2',
                      timeout: 60000 });
              console.log('PHP script triggered successfully');
              await browser.close();
          })();
          "
